In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


# steps you need if you are using scikit-learn and numpy for first time

In [2]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


# step 1: Importing useful packages

In [6]:
import numpy as np
#manipulate large multi-dimensional arrays 
import sklearn.preprocessing
#provides common utility functions and transformer classes to change raw feature vectors into more suitable for ML

# step 2: Defining sample data

In [11]:
input_data = np.array([2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                      [0.5, -7.9, 5.6],
                      [5.9, 2.3, -5.8])
#this will give error cause we have not passed the smaller arrays in individual array brackets

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [17]:
input_data = np.array([[2.1, -1.9, 5.5],
                      [-1.5, 2.4, 3.5],
                      [0.5, -7.9, 5.6],
                      [5.9, 2.3, -5.8]])

# step 3: data preprocessing techinique

# 1 Binarization

In [16]:
data_binarized = preprocessing.Binarizer(threshold = 0.5).transform(input_data)
print("\nBinarized data:\n",data_binarized)
# if import sklearn.preprocessing won't work try the code below "from sklearn import preprocessing"

NameError: name 'preprocessing' is not defined

In [18]:
from sklearn import preprocessing

In [19]:
data_binarized = preprocessing.Binarizer(threshold = 0.5).transform(input_data)
print("\nBinarized data:\n",data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


# 2 Mean Removal

In [22]:
print("Mean = ",input_data.mean(axis=0))
print("std deviation =",input_data.std(axis = 0))

Mean =  [ 1.75  -1.275  2.2  ]
std deviation = [2.71431391 4.20022321 4.69414529]


In [25]:
data_scaled = preprocessing.scale(input_data)
print("Mean = ",data_scaled.mean(axis=0))
print("std deviation = ",data_scaled.std(axis = 0))

Mean =  [1.11022302e-16 0.00000000e+00 0.00000000e+00]
std deviation =  [1. 1. 1.]


# 3 scaling

In [26]:
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\Min max scaled data:\n",data_scaled_minmax)

\Min max scaled data:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


# 4 Normalization

# L1 Normalization

In [27]:
# Normalize data
data_normalized_l1 = preprocessing.normalize(input_data,norm = 'l1')
print("\nL1 normalized data:\n",data_normalized_l1)
#least absolute devations. this normalization modifies the values so that the "sum of absolute values" is always upto 1 in each row


L1 normalized data:
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]


# L2 Normalization

In [28]:
# Normalize data
data_normalized_l2 = preprocessing.normalize(input_data,norm = 'l2')
print('\nL2 normalized data:\n',data_normalized_l2)
#referred to as least squares. this normalization modiefies the values "sum of the squares " is always upto 1 in each row


L2 normalized data:
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]


# Label encoding steps 

# step 1

In [29]:
import numpy as np
from sklearn import preprocessing

# step 2

In [30]:
# sample input labels
input_labels = ['red','black','red','green','black','yellow','white']

# step 3

In [31]:
#creating and training of label encodcer object
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

LabelEncoder()

# step 4

In [32]:
# encoding a set of labels
test_labels = ['green','red','black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =",test_labels)


Labels = ['green', 'red', 'black']


In [33]:
print("Encoded values =",list(encoded_values))

Encoded values = [1, 2, 0]


# step 5

In [35]:
# decoding a set of values
encoded_values = [3,0,4,1]
decoded_list = encoder.inverse_transform(encoded_values)
print("\nDecoded labels =",list(decoded_list))



Decoded labels = ['white', 'black', 'yellow', 'green']
